### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by GMTeams** [heimrichhannot/contao-google-tag-manager-bundle#1]
Contao 4.6.2
PHP 7.1.10

When I try to install via Contao manager, I get the following error message:

> Problem 1
>     - Conclusion: don't install heimrichhannot/contao-google-tag-manager-bundle 1.0.5
>     - Conclusion: don't install heimrichhannot/contao-google-tag-manager-bundle 1.0.4
>     - Conclusion: don't install heimrichhannot/contao-google-tag-manager-bundle 1.0.3
>     - Conclusion: don't install heimrichhannot/contao-google-tag-manager-bundle 1.0.2
>     - Conclusion: don't install heimrichhannot/contao-google-tag-manager-bundle 1.0.1
>     - Installation request for heimrichhannot/contao-google-tag-manager-bundle ^1.0 -> satisfiable by heimrichhannot/contao-google-tag-manager-bundle[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5].
>     - Conclusion: don't install symfony/framework-bundle v4.1.4
>     - heimrichhannot/contao-google-tag-manager-bundle 1.0.0 requires symfony/framework-bundle ^3.4 -> satisfiable by symfony/framework-bundle[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
>     - Can only install one of: symfony/framework-bundle[v3.4.0, v4.1.4].
>     - Can only install one of: symfony/framework-bundle[v3.4.1, v4.1.4].
>     - Can only install one of: symfony/framework-bundle[v3.4.10, v4.1.4].
>     - Can only install one of: symfony/framework-bundle[v3.4.11, v4.1.4].
>     - Can only install one of: symfony/framework-bundle[v3.4.12, v4.1.4].
>     - Can only install one of: symfony/framework-bundle[v3.4.13, v4.1.4].
>     - Can only install one of: symfony/framework-bundle[v3.4.14, v4.1.4].
>     - Can only install one of: symfony/framework-bundle[v3.4.15, v4.1.4].
>     - Can only install one of: symfony/framework-bundle[v3.4.2, v4.1.4].
>     - Can only install one of: symfony/framework-bundle[v3.4.3, v4.1.4].
>     - Can only install one of: symfony/framework-bundle[v3.4.4, v4.1.4].
>     - Can only install one of: symfony/framework-bundle[v3.4.5, v4.1.4].
>     - Can only install one of: symfony/framework-bundle[v3.4.6, v4.1.4].
>     - Can only install one of: symfony/framework-bundle[v3.4.7, v4.1.4].
>     - Can only install one of: symfony/framework-bundle[v3.4.8, v4.1.4].
>     - Can only install one of: symfony/framework-bundle[v3.4.9, v4.1.4].
>     - Installation request for symfony/framework-bundle (locked at v4.1.4) -> satisfiable by symfony/framework-bundle[v4.1.4].

Could you please help me with this - thanks!

**Comment by fatcrobat** [comment]
Thanks, should be fixed.
